pluginManagement {
    repositories {
        maven { url "https://fabricmc.net" }
        maven { url "https://gradle.org" }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven { url "https://fabricmc.net" }
    }
}

rootProject.name = "combat-roll-fix"
